export type Continent =
  | 'Europe'
  | 'North America'
  | 'South America'
  | 'Asia'
  | 'Oceania'
  | 'Africa'
  | 'Middle East'

export interface Country {
  readonly code: string
  readonly name: string
  readonly continent: Continent
}

export const COUNTRIES: readonly Country[] = [
  // Europe
  { code: 'AD', name: 'Andorra', continent: 'Europe' },
  { code: 'AL', name: 'Albania', continent: 'Europe' },
  { code: 'AT', name: 'Austria', continent: 'Europe' },
  { code: 'AX', name: 'Åland Islands', continent: 'Europe' },
  { code: 'BA', name: 'Bosnia and Herzegovina', continent: 'Europe' },
  { code: 'BE', name: 'Belgium', continent: 'Europe' },
  { code: 'BG', name: 'Bulgaria', continent: 'Europe' },
  { code: 'BY', name: 'Belarus', continent: 'Europe' },
  { code: 'CH', name: 'Switzerland', continent: 'Europe' },
  { code: 'CY', name: 'Cyprus', continent: 'Europe' },
  { code: 'CZ', name: 'Czechia', continent: 'Europe' },
  { code: 'DE', name: 'Germany', continent: 'Europe' },
  { code: 'DK', name: 'Denmark', continent: 'Europe' },
  { code: 'EE', name: 'Estonia', continent: 'Europe' },
  { code: 'ES', name: 'Spain', continent: 'Europe' },
  { code: 'FI', name: 'Finland', continent: 'Europe' },
  { code: 'FO', name: 'Faroe Islands', continent: 'Europe' },
  { code: 'FR', name: 'France', continent: 'Europe' },
  { code: 'GB', name: 'United Kingdom', continent: 'Europe' },
  { code: 'GG', name: 'Guernsey', continent: 'Europe' },
  { code: 'GI', name: 'Gibraltar', continent: 'Europe' },
  { code: 'GR', name: 'Greece', continent: 'Europe' },
  { code: 'HR', name: 'Croatia', continent: 'Europe' },
  { code: 'HU', name: 'Hungary', continent: 'Europe' },
  { code: 'IE', name: 'Ireland', continent: 'Europe' },
  { code: 'IM', name: 'Isle of Man', continent: 'Europe' },
  { code: 'IS', name: 'Iceland', continent: 'Europe' },
  { code: 'IT', name: 'Italy', continent: 'Europe' },
  { code: 'JE', name: 'Jersey', continent: 'Europe' },
  { code: 'LI', name: 'Liechtenstein', continent: 'Europe' },
  { code: 'LT', name: 'Lithuania', continent: 'Europe' },
  { code: 'LU', name: 'Luxembourg', continent: 'Europe' },
  { code: 'LV', name: 'Latvia', continent: 'Europe' },
  { code: 'MC', name: 'Monaco', continent: 'Europe' },
  { code: 'MD', name: 'Moldova', continent: 'Europe' },
  { code: 'ME', name: 'Montenegro', continent: 'Europe' },
  { code: 'MK', name: 'North Macedonia', continent: 'Europe' },
  { code: 'MT', name: 'Malta', continent: 'Europe' },
  { code: 'NL', name: 'Netherlands', continent: 'Europe' },
  { code: 'NO', name: 'Norway', continent: 'Europe' },
  { code: 'PL', name: 'Poland', continent: 'Europe' },
  { code: 'PT', name: 'Portugal', continent: 'Europe' },
  { code: 'RO', name: 'Romania', continent: 'Europe' },
  { code: 'RS', name: 'Serbia', continent: 'Europe' },
  { code: 'RU', name: 'Russia', continent: 'Europe' },
  { code: 'SE', name: 'Sweden', continent: 'Europe' },
  { code: 'SI', name: 'Slovenia', continent: 'Europe' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', continent: 'Europe' },
  { code: 'SK', name: 'Slovakia', continent: 'Europe' },
  { code: 'SM', name: 'San Marino', continent: 'Europe' },
  { code: 'UA', name: 'Ukraine', continent: 'Europe' },
  { code: 'VA', name: 'Vatican City', continent: 'Europe' },
  { code: 'XK', name: 'Kosovo', continent: 'Europe' },

  // North America
  { code: 'AG', name: 'Antigua and Barbuda', continent: 'North America' },
  { code: 'AI', name: 'Anguilla', continent: 'North America' },
  { code: 'AW', name: 'Aruba', continent: 'North America' },
  { code: 'BB', name: 'Barbados', continent: 'North America' },
  { code: 'BL', name: 'Saint Barthélemy', continent: 'North America' },
  { code: 'BM', name: 'Bermuda', continent: 'North America' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', continent: 'North America' },
  { code: 'BS', name: 'Bahamas', continent: 'North America' },
  { code: 'BZ', name: 'Belize', continent: 'North America' },
  { code: 'CA', name: 'Canada', continent: 'North America' },
  { code: 'CR', name: 'Costa Rica', continent: 'North America' },
  { code: 'CU', name: 'Cuba', continent: 'North America' },
  { code: 'CW', name: 'Curaçao', continent: 'North America' },
  { code: 'DM', name: 'Dominica', continent: 'North America' },
  { code: 'DO', name: 'Dominican Republic', continent: 'North America' },
  { code: 'GD', name: 'Grenada', continent: 'North America' },
  { code: 'GL', name: 'Greenland', continent: 'North America' },
  { code: 'GP', name: 'Guadeloupe', continent: 'North America' },
  { code: 'GT', name: 'Guatemala', continent: 'North America' },
  { code: 'HN', name: 'Honduras', continent: 'North America' },
  { code: 'HT', name: 'Haiti', continent: 'North America' },
  { code: 'JM', name: 'Jamaica', continent: 'North America' },
  { code: 'KN', name: 'Saint Kitts and Nevis', continent: 'North America' },
  { code: 'KY', name: 'Cayman Islands', continent: 'North America' },
  { code: 'LC', name: 'Saint Lucia', continent: 'North America' },
  { code: 'MF', name: 'Saint Martin', continent: 'North America' },
  { code: 'MQ', name: 'Martinique', continent: 'North America' },
  { code: 'MS', name: 'Montserrat', continent: 'North America' },
  { code: 'MX', name: 'Mexico', continent: 'North America' },
  { code: 'NI', name: 'Nicaragua', continent: 'North America' },
  { code: 'PA', name: 'Panama', continent: 'North America' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', continent: 'North America' },
  { code: 'PR', name: 'Puerto Rico', continent: 'North America' },
  { code: 'SV', name: 'El Salvador', continent: 'North America' },
  { code: 'SX', name: 'Sint Maarten', continent: 'North America' },
  { code: 'TC', name: 'Turks and Caicos Islands', continent: 'North America' },
  { code: 'TT', name: 'Trinidad and Tobago', continent: 'North America' },
  { code: 'US', name: 'United States', continent: 'North America' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', continent: 'North America' },
  { code: 'VG', name: 'British Virgin Islands', continent: 'North America' },
  { code: 'VI', name: 'U.S. Virgin Islands', continent: 'North America' },

  // South America
  { code: 'AR', name: 'Argentina', continent: 'South America' },
  { code: 'BO', name: 'Bolivia', continent: 'South America' },
  { code: 'BR', name: 'Brazil', continent: 'South America' },
  { code: 'CL', name: 'Chile', continent: 'South America' },
  { code: 'CO', name: 'Colombia', continent: 'South America' },
  { code: 'EC', name: 'Ecuador', continent: 'South America' },
  { code: 'FK', name: 'Falkland Islands', continent: 'South America' },
  { code: 'GF', name: 'French Guiana', continent: 'South America' },
  { code: 'GY', name: 'Guyana', continent: 'South America' },
  { code: 'PE', name: 'Peru', continent: 'South America' },
  { code: 'PY', name: 'Paraguay', continent: 'South America' },
  { code: 'SR', name: 'Suriname', continent: 'South America' },
  { code: 'UY', name: 'Uruguay', continent: 'South America' },
  { code: 'VE', name: 'Venezuela', continent: 'South America' },

  // Asia
  { code: 'AF', name: 'Afghanistan', continent: 'Asia' },
  { code: 'BD', name: 'Bangladesh', continent: 'Asia' },
  { code: 'BN', name: 'Brunei', continent: 'Asia' },
  { code: 'BT', name: 'Bhutan', continent: 'Asia' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', continent: 'Asia' },
  { code: 'CN', name: 'China', continent: 'Asia' },
  { code: 'CX', name: 'Christmas Island', continent: 'Asia' },
  { code: 'HK', name: 'Hong Kong', continent: 'Asia' },
  { code: 'ID', name: 'Indonesia', continent: 'Asia' },
  { code: 'IN', name: 'India', continent: 'Asia' },
  { code: 'IO', name: 'British Indian Ocean Territory', continent: 'Asia' },
  { code: 'JP', name: 'Japan', continent: 'Asia' },
  { code: 'KG', name: 'Kyrgyzstan', continent: 'Asia' },
  { code: 'KH', name: 'Cambodia', continent: 'Asia' },
  { code: 'KP', name: 'North Korea', continent: 'Asia' },
  { code: 'KR', name: 'South Korea', continent: 'Asia' },
  { code: 'KZ', name: 'Kazakhstan', continent: 'Asia' },
  { code: 'LA', name: 'Laos', continent: 'Asia' },
  { code: 'LK', name: 'Sri Lanka', continent: 'Asia' },
  { code: 'MM', name: 'Myanmar', continent: 'Asia' },
  { code: 'MN', name: 'Mongolia', continent: 'Asia' },
  { code: 'MO', name: 'Macao', continent: 'Asia' },
  { code: 'MV', name: 'Maldives', continent: 'Asia' },
  { code: 'MY', name: 'Malaysia', continent: 'Asia' },
  { code: 'NP', name: 'Nepal', continent: 'Asia' },
  { code: 'PH', name: 'Philippines', continent: 'Asia' },
  { code: 'PK', name: 'Pakistan', continent: 'Asia' },
  { code: 'SG', name: 'Singapore', continent: 'Asia' },
  { code: 'TH', name: 'Thailand', continent: 'Asia' },
  { code: 'TJ', name: 'Tajikistan', continent: 'Asia' },
  { code: 'TL', name: 'Timor-Leste', continent: 'Asia' },
  { code: 'TM', name: 'Turkmenistan', continent: 'Asia' },
  { code: 'TW', name: 'Taiwan', continent: 'Asia' },
  { code: 'UZ', name: 'Uzbekistan', continent: 'Asia' },
  { code: 'VN', name: 'Vietnam', continent: 'Asia' },

  // Middle East
  { code: 'AE', name: 'United Arab Emirates', continent: 'Middle East' },
  { code: 'AM', name: 'Armenia', continent: 'Middle East' },
  { code: 'AZ', name: 'Azerbaijan', continent: 'Middle East' },
  { code: 'BH', name: 'Bahrain', continent: 'Middle East' },
  { code: 'GE', name: 'Georgia', continent: 'Middle East' },
  { code: 'IL', name: 'Israel', continent: 'Middle East' },
  { code: 'IQ', name: 'Iraq', continent: 'Middle East' },
  { code: 'IR', name: 'Iran', continent: 'Middle East' },
  { code: 'JO', name: 'Jordan', continent: 'Middle East' },
  { code: 'KW', name: 'Kuwait', continent: 'Middle East' },
  { code: 'LB', name: 'Lebanon', continent: 'Middle East' },
  { code: 'OM', name: 'Oman', continent: 'Middle East' },
  { code: 'PS', name: 'Palestine', continent: 'Middle East' },
  { code: 'QA', name: 'Qatar', continent: 'Middle East' },
  { code: 'SA', name: 'Saudi Arabia', continent: 'Middle East' },
  { code: 'SY', name: 'Syria', continent: 'Middle East' },
  { code: 'TR', name: 'Turkey', continent: 'Middle East' },
  { code: 'YE', name: 'Yemen', continent: 'Middle East' },

  // Africa
  { code: 'AO', name: 'Angola', continent: 'Africa' },
  { code: 'BF', name: 'Burkina Faso', continent: 'Africa' },
  { code: 'BI', name: 'Burundi', continent: 'Africa' },
  { code: 'BJ', name: 'Benin', continent: 'Africa' },
  { code: 'BW', name: 'Botswana', continent: 'Africa' },
  { code: 'CD', name: 'DR Congo', continent: 'Africa' },
  { code: 'CF', name: 'Central African Republic', continent: 'Africa' },
  { code: 'CG', name: 'Congo', continent: 'Africa' },
  { code: 'CI', name: 'Côte d’Ivoire', continent: 'Africa' },
  { code: 'CM', name: 'Cameroon', continent: 'Africa' },
  { code: 'CV', name: 'Cape Verde', continent: 'Africa' },
  { code: 'DJ', name: 'Djibouti', continent: 'Africa' },
  { code: 'DZ', name: 'Algeria', continent: 'Africa' },
  { code: 'EG', name: 'Egypt', continent: 'Africa' },
  { code: 'EH', name: 'Western Sahara', continent: 'Africa' },
  { code: 'ER', name: 'Eritrea', continent: 'Africa' },
  { code: 'ET', name: 'Ethiopia', continent: 'Africa' },
  { code: 'GA', name: 'Gabon', continent: 'Africa' },
  { code: 'GH', name: 'Ghana', continent: 'Africa' },
  { code: 'GM', name: 'Gambia', continent: 'Africa' },
  { code: 'GN', name: 'Guinea', continent: 'Africa' },
  { code: 'GQ', name: 'Equatorial Guinea', continent: 'Africa' },
  { code: 'GW', name: 'Guinea-Bissau', continent: 'Africa' },
  { code: 'KE', name: 'Kenya', continent: 'Africa' },
  { code: 'KM', name: 'Comoros', continent: 'Africa' },
  { code: 'LR', name: 'Liberia', continent: 'Africa' },
  { code: 'LS', name: 'Lesotho', continent: 'Africa' },
  { code: 'LY', name: 'Libya', continent: 'Africa' },
  { code: 'MA', name: 'Morocco', continent: 'Africa' },
  { code: 'MG', name: 'Madagascar', continent: 'Africa' },
  { code: 'ML', name: 'Mali', continent: 'Africa' },
  { code: 'MR', name: 'Mauritania', continent: 'Africa' },
  { code: 'MU', name: 'Mauritius', continent: 'Africa' },
  { code: 'MW', name: 'Malawi', continent: 'Africa' },
  { code: 'MZ', name: 'Mozambique', continent: 'Africa' },
  { code: 'NA', name: 'Namibia', continent: 'Africa' },
  { code: 'NE', name: 'Niger', continent: 'Africa' },
  { code: 'NG', name: 'Nigeria', continent: 'Africa' },
  { code: 'RE', name: 'Réunion', continent: 'Africa' },
  { code: 'RW', name: 'Rwanda', continent: 'Africa' },
  { code: 'SC', name: 'Seychelles', continent: 'Africa' },
  { code: 'SD', name: 'Sudan', continent: 'Africa' },
  { code: 'SH', name: 'Saint Helena', continent: 'Africa' },
  { code: 'SL', name: 'Sierra Leone', continent: 'Africa' },
  { code: 'SN', name: 'Senegal', continent: 'Africa' },
  { code: 'SO', name: 'Somalia', continent: 'Africa' },
  { code: 'SS', name: 'South Sudan', continent: 'Africa' },
  { code: 'ST', name: 'São Tomé and Príncipe', continent: 'Africa' },
  { code: 'SZ', name: 'Eswatini', continent: 'Africa' },
  { code: 'TD', name: 'Chad', continent: 'Africa' },
  { code: 'TG', name: 'Togo', continent: 'Africa' },
  { code: 'TN', name: 'Tunisia', continent: 'Africa' },
  { code: 'TZ', name: 'Tanzania', continent: 'Africa' },
  { code: 'UG', name: 'Uganda', continent: 'Africa' },
  { code: 'YT', name: 'Mayotte', continent: 'Africa' },
  { code: 'ZA', name: 'South Africa', continent: 'Africa' },
  { code: 'ZM', name: 'Zambia', continent: 'Africa' },
  { code: 'ZW', name: 'Zimbabwe', continent: 'Africa' },

  // Oceania
  { code: 'AS', name: 'American Samoa', continent: 'Oceania' },
  { code: 'AU', name: 'Australia', continent: 'Oceania' },
  { code: 'CK', name: 'Cook Islands', continent: 'Oceania' },
  { code: 'FJ', name: 'Fiji', continent: 'Oceania' },
  { code: 'FM', name: 'Micronesia', continent: 'Oceania' },
  { code: 'GU', name: 'Guam', continent: 'Oceania' },
  { code: 'KI', name: 'Kiribati', continent: 'Oceania' },
  { code: 'MH', name: 'Marshall Islands', continent: 'Oceania' },
  { code: 'MP', name: 'Northern Mariana Islands', continent: 'Oceania' },
  { code: 'NC', name: 'New Caledonia', continent: 'Oceania' },
  { code: 'NF', name: 'Norfolk Island', continent: 'Oceania' },
  { code: 'NR', name: 'Nauru', continent: 'Oceania' },
  { code: 'NU', name: 'Niue', continent: 'Oceania' },
  { code: 'NZ', name: 'New Zealand', continent: 'Oceania' },
  { code: 'PF', name: 'French Polynesia', continent: 'Oceania' },
  { code: 'PG', name: 'Papua New Guinea', continent: 'Oceania' },
  { code: 'PN', name: 'Pitcairn Islands', continent: 'Oceania' },
  { code: 'PW', name: 'Palau', continent: 'Oceania' },
  { code: 'SB', name: 'Solomon Islands', continent: 'Oceania' },
  { code: 'TK', name: 'Tokelau', continent: 'Oceania' },
  { code: 'TO', name: 'Tonga', continent: 'Oceania' },
  { code: 'TV', name: 'Tuvalu', continent: 'Oceania' },
  { code: 'VU', name: 'Vanuatu', continent: 'Oceania' },
  { code: 'WF', name: 'Wallis and Futuna', continent: 'Oceania' },
  { code: 'WS', name: 'Samoa', continent: 'Oceania' },
]

const CONTINENT_ORDER: readonly Continent[] = [
  'Europe',
  'North America',
  'South America',
  'Asia',
  'Middle East',
  'Africa',
  'Oceania',
]

export const COUNTRIES_SORTED: readonly Country[] = [...COUNTRIES].sort((a, b) => {
  const ai = CONTINENT_ORDER.indexOf(a.continent)
  const bi = CONTINENT_ORDER.indexOf(b.continent)
  if (ai !== bi) return ai - bi
  return a.name.localeCompare(b.name)
})

export interface CountryPreset {
  readonly id: string
  readonly label: string
  readonly codes: readonly string[]
}

const EU_CODES: readonly string[] = [
  'AT', 'BE', 'BG', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI',
  'FR', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'MT',
  'NL', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK',
]

const ENGLISH_SPEAKING_CODES: readonly string[] = ['US', 'GB', 'CA', 'AU', 'NZ', 'IE']

const WORLDWIDE_CODES: readonly string[] = COUNTRIES.map((c) => c.code)

export const COUNTRY_PRESETS: readonly CountryPreset[] = [
  { id: 'eu', label: 'European Union', codes: EU_CODES },
  { id: 'en-speaking', label: 'English speaking', codes: ENGLISH_SPEAKING_CODES },
  { id: 'worldwide', label: 'Worldwide', codes: WORLDWIDE_CODES },
]

export function findCountry(code: string): Country {
  const upper = code.toUpperCase()
  const match = COUNTRIES.find((c) => c.code === upper)
  return match ?? { code: upper, name: upper, continent: 'Europe' }
}
